# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        files: \.(md|yml|yaml)
        args: [--prose-wrap=preserve]
